### ISSUE TITLE
How to get email through facebook backend?

### ISSUE THREAD

**Issue by jobec** [greenpau/caddy-auth-portal#136]
**Describe the issue**

I'm using the facebook backend and try to assign roles based on peoples email address. But when fetching a users profile from facebook, there's no email address included.

**Configuration**

Paste full `Caddyfile` below:

```
https://example.com {
    route /auth* {
        auth_portal {
            backends {
                facebook_oauth2_backend {
                    method oauth2
                    realm facebook
                    provider facebook
                    client_id 123
                    client_secret xxxx

                    user someone@gmail.com add role verified
                }
            }
            jwt {
                token_name access_token
                token_secret xxx
                token_lifetime 43200
                token_sign_method HS256
            }
        }
    }

    route /* {
        jwt {
            primary yes
            trusted_tokens {
                static_secret {
                    token_name access_token
                    token_secret xxx
                }
            }
            auth_url /auth
            allow roles verified
        }

```

**Version Information**

```
caddy-auth-portal@v1.4.6
```

**Expected behavior**

The email address is retrieved from facebook and a role is assigned based on that email.

**Comment by greenpau** [comment]
@jobec , I will take a look at it now.

**Comment by greenpau** [comment]
@jobec , when a user logs in, the plugin receives basic info about a user, e.g.:

```
{
  "id": "123456789",
  "first_name": "Paul",
  "last_name": "Greenberg",
  "name": "Paul Greenberg"
}
```

The `id` field is the unique identifier for a user in `graph.facebook.com` service.

The Facebook and Github implementation is very similar as it related to OAuth 2.0.

Upon receiving an access token, the plugin tries fetching user attributes from the Facebook/Github API.

https://github.com/greenpau/caddy-auth-portal/blob/a33efeeb9bc9ff18264698e7ffa98875dfaef26f/pkg/backends/oauth2/authenticate.go#L114-L119

For Facebook, I pass the following settings: `id,first_name,last_name,name,email`

https://github.com/greenpau/caddy-auth-portal/blob/a33efeeb9bc9ff18264698e7ffa98875dfaef26f/pkg/backends/oauth2/user.go#L56-L70

The reason I am not getting email is because I did not configure Facebook app to request email info:

![image](https://user-images.githubusercontent.com/3826416/123516685-66d4d100-d66b-11eb-9318-59116543d4a3.png)

Source: https://developers.facebook.com/docs/permissions/reference#e

## How do you get access to email

First, you need to switch to "Advanced Access".

![image](https://user-images.githubusercontent.com/3826416/123516816-03976e80-d66c-11eb-8ec8-28d18a1df3b8.png)

Second, you need to click "Get Advanced Access"

![image](https://user-images.githubusercontent.com/3826416/123516841-35103a00-d66c-11eb-8c14-e5a4c92b6282.png)

Once granted, you should see it being available.

![image](https://user-images.githubusercontent.com/3826416/123516964-cd0e2380-d66c-11eb-8c93-63d43a1b2611.png)

Next, you have to go through "Data Use Checkup"

![image](https://user-images.githubusercontent.com/3826416/123517406-bcf74380-d66e-11eb-9ae3-e2a726e9c827.png)

Once completed, you get an alert

![image](https://user-images.githubusercontent.com/3826416/123517431-ddbf9900-d66e-11eb-8a7a-a915d985c4d6.png)

**Comment by greenpau** [comment]
Now, @jobec , I have a better proposal for you. Switch your config to the latest plugin syntax. Then, use `transform user` directive to grant user roles.

> Switch your config to the latest plugin syntax

Provide your full config here. I will provide a replacement config.

> Then, use `transform user` directive to grant user roles.

Say your basic info look like this:

```
{
  "id": "123456789",
  "first_name": "Paul",
  "last_name": "Greenberg",
  "name": "Paul Greenberg"
}
```

You could create a user transform that would match Facebook as provider and the id of `123456789`.

```
      transform user {
        exact match sub 123456789
        exact match origin facebook
        action add role verified
      }
```

Now, you current config should be rewritten as:

```
https://example.com {
    route /auth* {
        authp {
            crypto default token lifetime 3600
            crypto key sign-verify 92becaac-403d-4ae0-870a-444f5c7b4bc9
            backends {
                facebook_oauth2_backend {
                    method oauth2
                    realm facebook
                    provider facebook
                    client_id 123
                    client_secret xxxx
                }
            }
            ui {
              links {
                "My Identity" "/auth/whoami" icon "las la-star"
                "My App" "/" icon "las la-star"
              }
            }
            enable source ip tracking
            transform user {
              exact match sub 123456789
              exact match origin facebook
              action add role verified
            }
        }
    }

    route /* {
        jwt {
            primary yes
            crypto key verify 92becaac-403d-4ae0-870a-444f5c7b4bc9
            set auth url /auth
            allow roles verified
        }
        respond * "authenticated" 200
    }
}
```

After login, when I browse to "My Identity" page, I would see the verified role added.

![image](https://user-images.githubusercontent.com/3826416/123518034-33e20b80-d672-11eb-9195-d4c8d6d6641a.png)

Hope this helps!

**Comment by greenpau** [comment]
@jobec, additionally, if you have a single server, then you can remove the `crypto key` from `portal` and `jwt`, because they will auto-generate ECDSA key for the server.
