### ISSUE TITLE
Caddyfile is not valid when enabling MFA

### ISSUE THREAD

**Issue by adrienyhuel** [greenpau/caddy-auth-portal#147]
**Describe the issue**

When I try to activate MFA globally like shown in doc, caddy can't start.

Error is : Error during parsing: parsing caddyfile tokens for 'authp': /etc/caddy/Caddyfile:63 - Error during parsing: auth backend local_backend subdirective require is unsupported

**Configuration**

Paste full `Caddyfile` below:

```
route @auth {
    authp {
      cookie domain adrien60.ovh
      cookie insecure on
      backends {
        local_backend {
          method local
          path /etc/caddy/assets/conf/local/auth/user_db.json
          realm local
          require mfa
        }
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.12
http.handlers.authp v1.4.14
```

**Expected behavior**

Module should accept "require mfa" in Caddyfile, to enable MFA for all users.

**Additional context**

**Comment by greenpau** [comment]
@adrienyhuel , the MFA is now enforced using `transform user` directive. See [User Transforms](https://github.com/greenpau/caddy-auth-portal#user-transforms).

Change your config:

```
route @auth {
    authp {
      cookie domain adrien60.ovh
      cookie insecure on
      backend local /etc/caddy/assets/conf/local/auth/user_db.json local
      transform user {
        match origin local
        require mfa
      }
```

Caveats:
* if a user does not have MFA configured, the user would not be able to get in. FYI, next week, I am going to add MFA onboarding as part of the login process where users do not have configured token
* the U2F tokens do not work at the moment. I did not port that code yet. Hopefully, next week.
* the user transform enforces mfa for the users authenticated via local backend only. This way if you have OAuth2.0 configured, it will not be enforces, because there is no way, at the moment, to configure MFA for OAuth2.0 users.

Hope this helps!

**Comment by adrienyhuel** [comment]
@greenpau  thank you it works now !

I saw the transform way to do it, but I thought it was only to match one user or one group.
You should remove from doc the old way to enforce MFA :)

**Comment by greenpau** [comment]
> I saw the transform way to do it, but I thought it was only to match one user or one group.

@adrienyhuel , you can match on any of these fields: https://github.com/greenpau/caddy-auth-jwt/blob/1f8db0897d282bc4de70efe228e136126a43818c/pkg/acl/condition.go#L29-L41

The conditions doc is over here: https://github.com/greenpau/caddy-auth-jwt#conditions

I hope I will make a video about all of this one day 😃 

>  You should remove from doc the old way to enforce MFA :)

👍
