### ISSUE TITLE
feature: Allow a login_hint parameter to be passed on to the OAuth2 provider

### ISSUE THREAD

**Issue by PedroDBFlores** [greenpau/caddy-auth-portal#219]
For some OAuth2 providers, there is a possibility of providing a login_hint parameter that will prefill the user's login on that provider (usually email).

I'd like to add support to forward on the login_hint to the OAuth provided if provided in the request parameters. I've created a PR [here](https://github.com/greenpau/caddy-auth-portal/pull/217) with the required changes.

**Comment by greenpau** [comment]
@PedroDBFlores , thank you! Let's manage the discussion in this issue.

Relevant Issues:
* https://github.com/greenpau/caddy-authorize/issues/96

PRs:
* https://github.com/greenpau/caddy-authorize/pull/95
* https://github.com/greenpau/caddy-auth-portal/pull/217

**Comment by greenpau** [comment]
@PedroDBFlores,

1. per PR #217, all you are doing is passing `login_hint` from query parameters from the redirect to the portal to authorization request to OAuth provider. Correct?

This PR looks good.

2. per PR greenpau/caddy-authorize#95, what is the point of setting it to an individual email, e.g. `set login hint foo@bar.net`? Is the assumption here that only a single user the endpoint?

from [OpenID Connect ](https://developers.google.com/identity/protocols/oauth2/openid-connect#server-flow):

> login_hint can be the user's email address or the sub string, which is equivalent to the user's Google ID. If you do not provide a login_hint and the user is currently logged in, the consent screen includes a request for approval to release the user's email address to your app. (Read more at login_hint.)

**Comment by PedroDBFlores** [comment]
Hello.

1. Yes that's correct
1. You can provide one only, but we've implemented the functionality to pass in a query parameter so it can be dynamic.

**Comment by greenpau** [comment]
> Yes that's correct

@PedroDBFlores , merging.

> You can provide one only, but we've implemented the functionality to pass in a query parameter so it can be dynamic.

Let me think through how to do it better. I think setting `login hint` is not optimal. Rather, I think you can get the email on the expired token and pass it as a hint. Thoughts?

**Comment by PedroDBFlores** [comment]
That could be a possibility true, but the usecase that I was going for is in the situation where the user isn't authenticated and I know an email that matches this user (for example by following an URL from an email to our server), then it would provide the email as a query parameter.

**Comment by greenpau** [comment]
> I know an email that matches this user (for example by following an URL from an email to our server), then it would provide the email as a query parameter.

@PedroDBFlores , do mind diagramming it? Are you saying that a user accesses WebsiteA (non-caddy) and then gets redirected to WebsiteB (caddy w/authorize supporting login hint) having the `login_hint` in query parameters?

**Comment by lennartschoch** [comment]
Hi @greenpau,
Let me jump in here as I am helping @PedroDBFlores out with his project and I think I can give a bit of context about this.

Our usecase is the following:
When a (not logged in) user firstly opens our web app, we're able to make an API call that provides us with some metadata about the user, including their email address.
We would like to use this email address as a login_hint later in the user journey, once the user is being redirected to the auth url, so that their email address is already pre-filled when they log in or sign up.

As all of this is happening within the same Caddy app, it doesn't really matter how the login_hint is passed to the auth url, it could be through a query parameter (as implemented in the PR), but also through a cookie.

Maybe it helps if we implement the assignment of the login_hint either by a fixed string, a query parameter or a cookie? I guess that those would be the most common ways that developers would use the login_hint.

Also, I was wondering whether using placeholders (e.g. `{http.request.uri.query.foo}`) is the preferred way of dynamically assigning values in this plugin?
When looking at other commands (like `crypto key my_id verify from env foo`), it seems like we might also implement the syntax of this new command like `set login hint from <cookie|query> foo`. Do you have a preference here?

**Comment by greenpau** [comment]
>  When looking at other commands (like crypto key my_id verify from env foo), it seems like we might also implement the syntax of this new command like set login hint from <cookie|query> foo. Do you have a preference here?

@PedroDBFlores , @lennartschoch , please see my response https://github.com/greenpau/caddy-authorize/issues/96#issuecomment-1008046436 

Let's continue there. Closing this thread.
