### ISSUE TITLE
claims and grpcweb

### ISSUE THREAD

**Issue by joe-getcouragenow** [greenpau/caddy-auth-portal#34]
Hey @greenpau 

Thank you for all the work on the auth and jwt and portal for caddy.

I am looking at using them in our project.
Caddy V2 looks excellent btw. Its really matured
The config system per module is perfect for us as our Code is modular.

Anyways ...

We are using a flutter GUI but i think its fine to use it with your Auth modules because flutter Webview can be used to open the Portal Login, which is better because then users see the TLS Certificate on web, desktop and mobile, which is a requirement for users to see in a mobile app that they are on HTTPS.
Here is how: https://medium.com/flutter-community/inappwebview-the-real-power-of-webviews-in-flutter-c6d52374209d

Now i was wondering about the claims in your jwt module.  At the moment its in the TODO basket of your module. 
I think that claims would be needed for us because flutter is a PWA, and so we need to allow flutter layer to check them so that in app authz routes are respected, so that we can control what GUI nav is shown to the user, so they dont get false GUI nav with things they cant access after they signed in.

The other sticky one if that we use GRPC Web, and so use the improbable GRPC code to do that.
https://github.com/improbable-eng/grpc-web/blob/master/go/grpcwebproxy/main.go#L17
There is a Caddy v1 module here: https://github.com/pieterlouw/caddy-grpc

Maybe you have some suggestions or tips, etc.

But i just wanted to raise this issue to visit the idea of using your code and what hurdles we face.

**Comment by greenpau** [comment]
> At the moment its in the TODO basket of your module.

@joe-getcouragenow , which module are you referring to? `jwt` or `portal`?

> I think that claims would be needed for us because flutter is a PWA

Currently, role based (group based) access control works as described https://github.com/greenpau/caddy-auth-jwt#sources-of-role-information.

There are a lot of ideas in this issue! 😄 I think it is best you have an issue per idea. Also, you want to be specific as to "authentication" (`portal` repo) or "authorization" (`jwt` repo), because the two are pretty much independent. 

Finally, I will help you getting where you want to be! 😉

**Comment by greenpau** [comment]
Opened https://github.com/greenpau/caddy-auth-jwt/issues/27, closing this one.
