### ISSUE TITLE
request for advice - I need to add roles to the jwt / claim header for LDAP

### ISSUE THREAD

**Issue by SvenDowideit** [greenpau/caddy-auth-portal#84]
but I can't add groups to the LDAP service

I'm wondering if there's a right way to modify the jwt from a downstream plugin, or if there's some other way it would make sense when using caddy-auth-portal.

these roles are expected to be managed by non-ops, so modifying the caddyfile isn't really going to work (well)

mostly, I'm curious to know how you'd do it  :)

**Comment by greenpau** [comment]
> these roles are expected to be managed by non-ops, so modifying the caddyfile isn't really going to work (well)

@SvenDowideit , say LDAP user object has a number of groups associated with it. These groups could be either distribution lists or security groups. At first, it seems reasonable to dynamically figure out which ones are "security groups" and add them as role names. Now, ask yourself:

- Do I put the entire DN as role name?
- How do I determine which groups I am interested in?

That's why defining a set of specific groups associated with specific roles is a good idea: 
https://github.com/greenpau/caddy-auth-portal/blob/a56fc4f223b28e543d7a4c99c7edf7cc423dce3b/assets/conf/ldap/Caddyfile#L34-L38

I would create 3 (or so) LDAP security groups for each app. Next, each app would need to have an ID, i.e. `app_id`.

Then, role would be `<app_id>_admin`, `<app_id>_editor`, `<app_id>_viewer`...

**Comment by SvenDowideit** [comment]
That's the problem, the LDAP we're using for authentication has no groups, and we can't add any (for reasons) - and we want to manage roles (ie, authorization) in an application specific way

So the LDAP group -> role approach can't be used - and I'm wondering what you'd do instead.

**Comment by greenpau** [comment]
> the LDAP we're using for authentication has no groups

@SvenDowideit , what is the source of "authorization" information, i.e. what a particular user is allowed/prohibited to access?

**Comment by SvenDowideit** [comment]
Probably a separate database or file.
That's part of what I'm asking... We can't modify LDAP, but we can setup anything as an extra service.

**Comment by greenpau** [comment]
@SvenDowideit , I would recommend setting up https://www.keycloak.org/ server and one-way synching identities from LDAP. Then, enhancing identities with group/role data in keycloak. Then, exposing OAuth2.0 interface. Then, within this plugin, you do OAuth2.0 integration and you are all set. See also https://github.com/greenpau/caddy-auth-portal/issues/74#issuecomment-741058767

**Comment by SvenDowideit** [comment]
ah, fair enough - I'm working to move away from keycloak - we have low traffic sites where its more useful to be as lightweight as possible.
So i'm thinking i'll look into either making a local modification of your code, or having a downstream plugin modify / replace the jwt that you're making in caddy-auth-portal - just adding roles, using some simple data-store (likely start with json file, and then use some database we already have lying around)

we'll see - I'm also mildly interested in open policy agent / cas rules, but I want to prototype something early next week.
